execution_engine: asyncio
logger:
  transports: [console]
  level: debug
  path: "logs/mcp-agent.jsonl"
mcp:
  servers:
    GramTaskboard:
      command: "npx"
      args: [
        "mcp-remote",
        "https://app.getgram.ai/mcp/<your-gram-url>",
        "--header",
        "MCP-TASKBOARD-SERVER-URL:${TASKBOARD_SERVER_URL}"
      ]
openai:
  api_key: "${OPENAI_API_KEY}"
  default_model: "gpt-4o-mini"
  reasoning_effort: "medium"
