[project]
name = "mcp-fastapi-chat"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.116.1",
    "mcp-agent>=0.1.8",
    "uvicorn>=0.35.0",
]
